### ISSUE TITLE
Windows release

### ISSUE THREAD

**Issue by kr-stn** [noahsw/highlight-hunter#2]
Hi,

I was wondering if it would be possible to upload the Windows version of 2.3 analogue to [the Mac release?](https://github.com/noahsw/highlight-hunter/releases/download/2.3-mac-open-sourced/Highlight.Hunter.Pro.2.3.zip)

I am unable to build from source with VS2012 Express and can't find any place that has pre-compiled windows binaries.

**Comment by noahsw** [comment]
Unfortunately I don't have my Windows environment up and running anymore but I was able to find an old installer on my machine.

https://github.com/noahsw/highlight-hunter/releases/tag/2.1-windows-installer

Let me know if this works for you.

**Comment by kr-stn** [comment]
Works like a charm (Win10 x64). Thank you so much!

**Comment by noahsw** [comment]
Excellent. Glad to hear!
